meta_product_name: "Hair'Diag"
meta_title: "Hair'Diag - La solution à votre chute de cheveux"
meta_description: "Grâce à Hair'Diag, obtenez l'avis d'un dermatologue spécialiste du cuir chevelu, en 48h seulement"
meta_image: "cover.jpg"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
