# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e5c9e635b9f9a856a0310859258225dad0a235a241dd89e50a222941a15683f1224e686a60d38f67b2621fc04bc55d7dbff5cac99ff1c8a53dcb644fd0334c

test:
  secret_key_base: 8e623eb55416eb4df5a73932f56f639c35e74c8eb0e0a4871191df088505bb401a0f7b285f3002a6d6f39f7555eef671563e737ca2c51ba6ab5454e1c214111f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
